markdown: kramdown
kramdown:
    input: GFM
    toc_levels: 2..6

exclude: [_build]

gems:
    # https://github.com/jekyll/jekyll-redirect-from
    # case insensitive
    - jekyll-redirect-from
    - jekyll-sitemap
